language: cpp
compiler: gcc

# env: CMAKE_CMD_OPTION="-DENABLE_TESTING=1 "

# matrix:
#   include:
#     - os: linux
#       sudo: false
#       dist: trusty
#       compiler: gcc
# addons:
#   apt:
#     packages:
#       - make
#       - lcov
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      - "python3-setuptools"

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install --upgrade norminette

jobs:
  include:
    - stage: build
      script:
       - make
       - make test
    - stage: test
      script:
       - make test_run
    - stage: norminette
      script:
       - echo "Running norminette\n"
       - ./run_norminette.sh
    
# Disable notifications
notifications:
  email: false
