language: cpp
compiler: gcc

env: CMAKE_CMD_OPTION="-DENABLE_TESTING=1 "

matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      compiler: gcc
addons:
  apt:
    packages:
      - make
      - lcov

jobs:
  include:
    - stage: build
      script:
        - make
        - make test
    - stage: test
      script:
        - make test_run
    - stage: norminette
      script:
        - echo "Running norminette\n"
    
# Disable notifications
notifications:
  email: false
