version: 2

jobs:
  build:
    docker:
      - image: "debian:buster"
    steps:
      - checkout
      - run:
          name: Install dependencies GCC
          command: 'apt-get update && apt-get install -y gcc make python3 python3-pip'
      - run:
          name: Install dependencies Python
          command: 'pip3 install -U pip && pip3 install -U setuptools && pip3 install -U norminette'
      - run:
          name: Build
          command: 'make && make test'
      - run:
          name: Test
          command: 'make test_run'
      - run:
          name: Norminette
          command: './run_norminette.sh'