version: 2

jobs:
  build:
    docker:
      - image: "debian:buster"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: 'apt-get update && apt-get install -y gcc make'
      - run:
          name: Build
          command: 'make && make test'
      - run:
          name: Test
          command: 'make test_run'
      - run:
          name: Norminette
          command: 'echo "Running norminette\n"'